"""initial

Revision ID: 16557111881b
Revises: 
Create Date: 2026-05-05 23:15:23.637397

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16557111881b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('event_type', sa.Integer(), nullable=False),
    sa.Column('event_type_name', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_log_event_success', 'audit_log', ['event_type', 'success'], unique=False)
    op.create_index(op.f('ix_audit_log_event_type'), 'audit_log', ['event_type'], unique=False)
    op.create_index(op.f('ix_audit_log_timestamp'), 'audit_log', ['timestamp'], unique=False)
    op.create_index('ix_audit_log_timestamp_user', 'audit_log', ['timestamp', 'user_id'], unique=False)
    op.create_index(op.f('ix_audit_log_user_id'), 'audit_log', ['user_id'], unique=False)
    op.create_table('login_attempts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('attempted_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_login_attempts_at', 'login_attempts', ['attempted_at'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('salt', sa.LargeBinary(), nullable=False),
    sa.Column('wrapped_master_key_cipher', sa.LargeBinary(), nullable=False),
    sa.Column('wrapped_master_key_nonce', sa.LargeBinary(), nullable=False),
    sa.Column('wrapped_master_key_tag', sa.LargeBinary(), nullable=False),
    sa.Column('totp_secret', sa.String(length=64), nullable=True),
    sa.Column('totp_last_counter', sa.Integer(), nullable=False),
    sa.Column('totp_enabled', sa.Boolean(), nullable=False),
    sa.Column('session_token_hash', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_session_token_hash'), 'users', ['session_token_hash'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('fido2_challenges',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('purpose', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('challenge', sa.LargeBinary(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fido2_challenges_expires_at'), 'fido2_challenges', ['expires_at'], unique=False)
    op.create_index(op.f('ix_fido2_challenges_purpose'), 'fido2_challenges', ['purpose'], unique=False)
    op.create_index('ix_fido2_challenges_purpose_expires', 'fido2_challenges', ['purpose', 'expires_at'], unique=False)
    op.create_index(op.f('ix_fido2_challenges_user_id'), 'fido2_challenges', ['user_id'], unique=False)
    op.create_table('password_entries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('version_id', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('title_search', sa.String(), nullable=True),
    sa.Column('ciphertext', sa.LargeBinary(), nullable=True),
    sa.Column('iv', sa.LargeBinary(), nullable=True),
    sa.Column('auth_tag', sa.LargeBinary(), nullable=True),
    sa.Column('key_metadata', sa.Text(), nullable=True),
    sa.Column('title_cipher', sa.String(), nullable=True),
    sa.Column('title_nonce', sa.String(), nullable=True),
    sa.Column('username_cipher', sa.String(), nullable=True),
    sa.Column('username_nonce', sa.String(), nullable=True),
    sa.Column('password_cipher', sa.String(), nullable=True),
    sa.Column('password_nonce', sa.String(), nullable=True),
    sa.Column('url_cipher', sa.String(), nullable=True),
    sa.Column('url_nonce', sa.String(), nullable=True),
    sa.Column('notes_cipher', sa.String(), nullable=True),
    sa.Column('notes_nonce', sa.String(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_password_entries_is_deleted'), 'password_entries', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_password_entries_title_search'), 'password_entries', ['title_search'], unique=False)
    op.create_index(op.f('ix_password_entries_user_id'), 'password_entries', ['user_id'], unique=False)
    op.create_table('recovery_codes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('code_hash', sa.String(length=255), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recovery_codes_user_id'), 'recovery_codes', ['user_id'], unique=False)
    op.create_table('webauthn_credentials',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('credential_id', sa.LargeBinary(), nullable=False),
    sa.Column('public_key', sa.LargeBinary(), nullable=False),
    sa.Column('sign_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('wrapped_master_key_fido_cipher', sa.LargeBinary(), nullable=False),
    sa.Column('wrapped_master_key_fido_nonce', sa.LargeBinary(), nullable=False),
    sa.Column('wrapped_master_key_fido_tag', sa.LargeBinary(), nullable=False),
    sa.Column('device_protector_cipher', sa.LargeBinary(), nullable=False),
    sa.Column('device_protector_nonce', sa.LargeBinary(), nullable=False),
    sa.Column('device_protector_tag', sa.LargeBinary(), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_webauthn_credentials_credential_id'), 'webauthn_credentials', ['credential_id'], unique=True)
    op.create_index(op.f('ix_webauthn_credentials_user_id'), 'webauthn_credentials', ['user_id'], unique=False)
    op.create_table('password_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entry_id', sa.Integer(), nullable=False),
    sa.Column('password_cipher', sa.String(), nullable=False),
    sa.Column('password_nonce', sa.String(), nullable=False),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['entry_id'], ['password_entries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_password_history_entry_id'), 'password_history', ['entry_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_password_history_entry_id'), table_name='password_history')
    op.drop_table('password_history')
    op.drop_index(op.f('ix_webauthn_credentials_user_id'), table_name='webauthn_credentials')
    op.drop_index(op.f('ix_webauthn_credentials_credential_id'), table_name='webauthn_credentials')
    op.drop_table('webauthn_credentials')
    op.drop_index(op.f('ix_recovery_codes_user_id'), table_name='recovery_codes')
    op.drop_table('recovery_codes')
    op.drop_index(op.f('ix_password_entries_user_id'), table_name='password_entries')
    op.drop_index(op.f('ix_password_entries_title_search'), table_name='password_entries')
    op.drop_index(op.f('ix_password_entries_is_deleted'), table_name='password_entries')
    op.drop_table('password_entries')
    op.drop_index(op.f('ix_fido2_challenges_user_id'), table_name='fido2_challenges')
    op.drop_index('ix_fido2_challenges_purpose_expires', table_name='fido2_challenges')
    op.drop_index(op.f('ix_fido2_challenges_purpose'), table_name='fido2_challenges')
    op.drop_index(op.f('ix_fido2_challenges_expires_at'), table_name='fido2_challenges')
    op.drop_table('fido2_challenges')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_session_token_hash'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index('ix_login_attempts_at', table_name='login_attempts')
    op.drop_table('login_attempts')
    op.drop_index(op.f('ix_audit_log_user_id'), table_name='audit_log')
    op.drop_index('ix_audit_log_timestamp_user', table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_timestamp'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_event_type'), table_name='audit_log')
    op.drop_index('ix_audit_log_event_success', table_name='audit_log')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
