[package]
name = "bitnet-totp"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
subtle = { workspace = true }
bitnet-crypto = { workspace = true }
base32 = { workspace = true }
url = { workspace = true }
thiserror = { workspace = true }

