[package]
name = "bitnet-cli"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[[bin]]
name = "bitnet-cli"
path = "src/main.rs"

[dependencies]
bitnet-totp = { workspace = true }
zeroize = { workspace = true }
bitnet-kdbx = { workspace = true }
bitnet-crypto = { workspace = true }
bitnet-core = { workspace = true }
bitnet-daemon = { workspace = true }
clap = { workspace = true }
rpassword = { workspace = true }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

