//! BitNet daemon — long-running process that holds an unlocked
//! vault and serves JSON-RPC commands over the IPC transport.
//!
//! Concurrency model:
//! - One `Mutex<DaemonState>` guards the in-process state so
//!   concurrent clients serialise.
//! - The IPC server accepts one client at a time. The protocol
//!   uses length-prefixed JSON frames (see `protocol`), so each
//!   `accept` call processes exactly one request/response pair.
//!
//! The actual vault operations are abstracted behind the
//! [`VaultService`] trait. The default implementation
//! ([`NoopVaultService`]) rejects every method with a
//! placeholder, which keeps the daemon testable in isolation.
//! Production wiring plugs in a real implementation that owns
//! a `bitnet_core::SessionManager`.

use std::io::{Read, Write};
use std::sync::Mutex;

use zeroize::Zeroize;

use crate::auth;
use crate::ipc::Conn;
use crate::protocol::{self, code, make_err, make_ok, Method, Request};

/// In-process state of the daemon. Wrapped in a `Mutex` so only
/// one request is being dispatched at a time.
pub struct DaemonState {
    /// Session token, or `None` when the vault is locked. Stored
    /// in a fixed-size 32-byte array so the [`Zeroize`] impl on
    /// `[u8; 32]` wipes it cleanly.
    ///
    /// [BITNET-H1] The token is **client-generated** and
    /// transmitted in the `unlock` request parameters — never
    /// returned by the daemon. This closes the leak where any
    /// process with a handle on the Named Pipe could read the
    /// `token_hex` field of the response.
    pub token: Option<[u8; 32]>,
    /// Highest `seq` value seen on a successfully-authenticated
    /// request. Used by the [BITNET-M3] replay check to ensure
    /// monotonic progression. Reset to `None` when the token is
    /// cleared (e.g. on `lock` or a new `unlock`).
    pub last_seq: Option<u64>,
    /// Graceful shutdown flag. Set to `true` when a `shutdown`
    /// request is received; the main accept loop checks this
    /// between iterations.
    pub shutdown: std::sync::atomic::AtomicBool,
}

impl DaemonState {
    /// Create an empty, locked daemon state.
    pub fn new() -> Self {
        Self {
            token: None,
            last_seq: None,
            shutdown: std::sync::atomic::AtomicBool::new(false),
        }
    }

    /// Whether the daemon currently holds a session token.
    pub fn has_token(&self) -> bool {
        self.token.is_some()
    }

    /// Arm the daemon with a fresh 32-byte session token.
    /// Replaces any previous token (which is zeroised) and
    /// resets the replay counter.
    pub fn set_token(&mut self, token: [u8; 32]) {
        if let Some(mut prev) = self.token.take() {
            prev.zeroize();
        }
        self.last_seq = None;
        self.token = Some(token);
    }

    /// Drop the session token. Returns `true` if a token was
    /// actually present (and zeroised).
    pub fn clear_token(&mut self) -> bool {
        if let Some(mut t) = self.token.take() {
            t.zeroize();
            self.last_seq = None;
            true
        } else {
            false
        }
    }

    /// Read-only view of the current token. Returns `None` when
    /// the vault is locked. Intended for HMAC verification.
    pub fn token(&self) -> Option<&[u8; 32]> {
        self.token.as_ref()
    }

    /// Highest `seq` value seen on a previously-authenticated
    /// request, or `None` if no protected request has been
    /// processed since the last `unlock`. Used by the
    /// [BITNET-M3] replay check.
    pub fn last_seq(&self) -> Option<u64> {
        self.last_seq
    }

    /// Record the highest `seq` value seen. The caller is
    /// responsible for ensuring the new value is strictly
    /// greater than the previous one (the dispatch loop in
    /// `dispatch` enforces this before calling).
    pub fn set_last_seq(&mut self, seq: u64) {
        self.last_seq = Some(seq);
    }
}

impl Default for DaemonState {
    fn default() -> Self {
        Self::new()
    }
}

impl Drop for DaemonState {
    fn drop(&mut self) {
        // Belt and suspenders: even if a caller forgot to call
        // `clear_token`, the destructor wipes the bytes.
        self.clear_token();
    }
}

/// Vault service trait. Implementations are responsible for the
/// real I/O (vault file path, master password, Argon2, KDBX).
/// The daemon only deals with the JSON-RPC envelope; the service
/// returns either a `serde_json::Value` payload (success) or an
/// `i32` error code from the [`code`] module.
///
/// All methods are synchronous and may block (Argon2, file I/O);
/// the daemon serialises calls on the [`Mutex<DaemonState>`].
pub trait VaultService: Send + Sync {
    /// Open a vault and store the client-supplied session token.
    /// The token is **generated by the client** and passed in
    /// `params.token_hex` — the daemon never invents a token, so
    /// the response to `unlock` carries no secret material.
    ///
    /// [BITNET-H1] CWE-200 / CWE-522: the previous API returned
    /// the new token in `token_hex` over the wire, allowing any
    /// process with a Named Pipe handle to read it. Under the
    /// client-generated model the daemon still holds the token
    /// (for HMAC verification on subsequent requests) but a
    /// network sniffer on the IPC channel learns nothing useful.
    ///
    /// `params` must include `{"path": "...", "token_hex": "<64 hex>"}`.
    /// The master password is not transmitted over the daemon
    /// IPC — the service is expected to prompt the user (e.g. via
    /// a TTY) or read it from a pre-shared keychain.
    fn unlock(&self, params: &serde_json::Value) -> Result<[u8; 32], i32>;

    /// Look up the entry list (no secrets, just metadata).
    fn list_entries(&self, _params: &serde_json::Value) -> Result<serde_json::Value, i32> {
        Err(code::UNKNOWN_METHOD)
    }

    /// Return the full entry (including password) for the given
    /// UUID. The daemon never logs this; the client is expected
    /// to zeroise the bytes after use.
    fn get_entry(&self, _params: &serde_json::Value) -> Result<serde_json::Value, i32> {
        Err(code::UNKNOWN_METHOD)
    }

    /// Compute a TOTP code for the given entry.
    fn totp(&self, _params: &serde_json::Value) -> Result<serde_json::Value, i32> {
        Err(code::UNKNOWN_METHOD)
    }

    /// Persist a new entry.
    fn add_entry(&self, _params: &serde_json::Value) -> Result<serde_json::Value, i32> {
        Err(code::UNKNOWN_METHOD)
    }

    /// Remove an entry by UUID.
    fn delete_entry(&self, _params: &serde_json::Value) -> Result<serde_json::Value, i32> {
        Err(code::UNKNOWN_METHOD)
    }

    /// Stateless password generation. Does not require auth.
    fn generate_password(&self, _params: &serde_json::Value) -> Result<serde_json::Value, i32> {
        Err(code::UNKNOWN_METHOD)
    }
}

/// Default [`VaultService`] implementation. Used by tests that
/// exercise the dispatch path without spinning up a real
/// `SessionManager`. The `unlock` path echoes the client's
/// `token_hex` (the daemon treats it as a black-box 32-byte
/// value — it does not need to be cryptographically random
/// here, only in production).
pub struct NoopVaultService;

impl VaultService for NoopVaultService {
    fn unlock(&self, params: &serde_json::Value) -> Result<[u8; 32], i32> {
        // [BITNET-H1] Extract the client-supplied token from params
        // instead of synthesising one. The daemon stores it
        // verbatim. If the field is missing or malformed, fall
        // back to a deterministic placeholder so the integration
        // tests (which still wire `dispatch` directly) keep
        // working.
        use crate::protocol::hex_decode_lower;
        if let Some(s) = params.get("token_hex").and_then(|v| v.as_str()) {
            if let Some(bytes) = hex_decode_lower(s) {
                if bytes.len() == 32 {
                    let mut out = [0u8; 32];
                    out.copy_from_slice(&bytes);
                    return Ok(out);
                }
            }
        }
        // Fallback for tests: deterministic test token.
        let mut token = [0u8; 32];
        for (i, b) in token.iter_mut().enumerate() {
            *b = i as u8;
        }
        Ok(token)
    }
}

/// Single-threaded dispatch of a request. The `Mutex<DaemonState>`
/// is held only for the duration of the auth check; the actual
/// method handler runs through the [`VaultService`] trait so it
/// can do slow operations (Argon2, file I/O) without blocking
/// the next caller.
pub fn dispatch<S: VaultService>(
    state: &Mutex<DaemonState>,
    service: &S,
    request: Request,
) -> serde_json::Value {
    let method = match Method::from_str(&request.method) {
        Some(m) => m,
        None => return make_err(request.id, code::UNKNOWN_METHOD, "unknown method"),
    };

    // `ping`, `unlock` and `shutdown` bypass auth. `ping` lets
    // clients detect whether the daemon is running; `unlock` is
    // the *only* way a client can obtain a session token, so
    // requiring auth on it would be a chicken-and-egg problem.
    // `shutdown` must be auth-free so the process owner can
    // stop the daemon even when the vault is locked.
    match method {
        Method::Ping => return make_ok(request.id, serde_json::json!({"pong": true})),
        Method::Unlock => {
            // Inline — see `Method::Unlock` arm in the service
            // match below. We do it here so the auth check below
            // is skipped entirely.
            //
            // [BITNET-H1] The token is supplied by the client in
            // `params.token_hex` and echoed back through the
            // service's return value. We persist it under the
            // lock and return ONLY an ack — no `token_hex` field
            // in the response, so a Named Pipe sniffer learns
            // nothing about the session secret.
            let new_token = match service.unlock(&request.params) {
                Ok(t) => t,
                Err(code) => {
                    return make_err(request.id, code, error_message_for_code(code));
                }
            };
            let mut g = state.lock().unwrap();
            g.set_token(new_token);
            return make_ok(request.id, serde_json::json!({"ok": true}));
        }
        Method::Shutdown => {
            state
                .lock()
                .unwrap()
                .shutdown
                .store(true, std::sync::atomic::Ordering::SeqCst);
            return make_ok(request.id, serde_json::json!({"ok": true}));
        }
        _ => {}
    }

    // All other methods require a token AND a valid HMAC.
    let token: [u8; 32] = {
        let guard = match state.lock() {
            Ok(g) => g,
            Err(e) => {
                tracing::error!(error = %e, "daemon state mutex poisoned");
                return make_err(request.id, code::INTERNAL, "internal error");
            }
        };
        match guard.token() {
            Some(t) => *t,
            None => return make_err(request.id, code::SESSION_LOCKED, "vault is locked"),
        }
    };

    // Re-serialise `params` to canonical bytes for HMAC. The same
    // bytes the client signed are what the daemon sees (the
    // protocol uses `serde_json::Value` which is deterministic
    // for the inputs we accept).
    let params_json = match serde_json::to_vec(&request.params) {
        Ok(b) => b,
        Err(e) => {
            return make_err(
                request.id,
                code::INVALID_PARAMS,
                format!("params re-serialise failed: {e}"),
            );
        }
    };

    // [BITNET-M3] CWE-294 / CWE-345: replay protection.
    // Every protected method must carry an `auth` HMAC plus a
    // monotonic `seq` and a fresh `ts`. The `seq`/`ts` are
    // included in the signed payload (see auth::sign_request) so
    // a captured frame cannot be re-played past the freshness
    // window or with a stale sequence number.
    //
    // Order of checks:
    //   1. If `auth` is missing → UNAUTHORIZED. (No auth means
    //      the caller did not prove knowledge of the token.)
    //   2. If `seq` or `ts` is missing → REPLAY. (Required for
    //      every protected method.)
    //   3. Verify the HMAC → UNAUTHORIZED on mismatch.
    //   4. Freshness window → REPLAY on skew > 30 s.
    //   5. Monotonic seq → REPLAY on `seq <= last_seen`.
    let (seq, ts) = match (request.seq, request.ts) {
        (Some(s), Some(t)) => (s, t),
        _ => {
            // No seq/ts — but still require an auth attempt
            // first so the error code matches the missing-auth
            // case rather than overloading REPLAY.
            if request.auth.is_none() {
                return make_err(request.id, code::UNAUTHORIZED, "auth required");
            }
            return make_err(
                request.id,
                code::REPLAY,
                "missing seq/ts for protected method",
            );
        }
    };

    let auth_ok = request
        .auth
        .as_deref()
        .map(|a| auth::verify_request(&token, &request.method, &params_json, seq, ts, a))
        .unwrap_or(false);
    if !auth_ok {
        return make_err(request.id, code::UNAUTHORIZED, "auth failed");
    }

    // Freshness check: |now - ts| <= MAX_REQUEST_AGE_SECS.
    let now = std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .map(|d| d.as_secs())
        .unwrap_or(0);
    let skew = now.abs_diff(ts);
    if skew > crate::protocol::MAX_REQUEST_AGE_SECS {
        return make_err(
            request.id,
            code::REPLAY,
            format!(
                "ts outside freshness window (skew={}s, max={}s)",
                skew,
                crate::protocol::MAX_REQUEST_AGE_SECS
            ),
        );
    }

    // Monotonic sequence check. We track the highest seq we've
    // seen on this token. A new seq must be strictly greater.
    // [BITNET-M3] The state lock is held only for the read+update
    // of the seq counter, then released before continuing the
    // dispatch.
    {
        let mut g = match state.lock() {
            Ok(g) => g,
            Err(_) => return make_err(request.id, code::INTERNAL, "internal error"),
        };
        if let Some(last) = g.last_seq() {
            if seq <= last {
                return make_err(
                    request.id,
                    code::REPLAY,
                    format!("seq={} <= last_seen={}", seq, last),
                );
            }
        }
        g.set_last_seq(seq);
    }

    // Dispatch to the service. `lock` and `is_unlocked` are
    // handled inline because they are state-only and need no
    // service backing.
    match method {
        Method::Lock => {
            let mut g = state.lock().unwrap();
            g.clear_token();
            make_ok(request.id, serde_json::json!({"ok": true}))
        }
        Method::IsUnlocked => {
            let g = state.lock().unwrap();
            make_ok(request.id, serde_json::json!({"unlocked": g.has_token()}))
        }
        Method::ListEntries => service_method(request.id, service.list_entries(&request.params)),
        Method::GetEntry => service_method(request.id, service.get_entry(&request.params)),
        Method::Totp => service_method(request.id, service.totp(&request.params)),
        Method::AddEntry => service_method(request.id, service.add_entry(&request.params)),
        Method::DeleteEntry => service_method(request.id, service.delete_entry(&request.params)),
        Method::GeneratePassword => {
            service_method(request.id, service.generate_password(&request.params))
        }
        // ping, unlock and shutdown were handled above; these
        // arms are unreachable but keep the match exhaustive.
        Method::Ping | Method::Unlock | Method::Shutdown => {
            unreachable!("handled in early return above")
        }
    }
}

/// Helper: convert a service `Result<Value, i32>` into the
/// JSON-RPC response envelope.
fn service_method(id: u64, result: Result<serde_json::Value, i32>) -> serde_json::Value {
    match result {
        Ok(value) => make_ok(id, value),
        Err(code) => make_err(id, code, error_message_for_code(code)),
    }
}

/// Return a short, user-facing message for a known error code.
/// Centralised here so the wire format stays consistent.
fn error_message_for_code(c: i32) -> &'static str {
    match c {
        code::OK => "ok",
        code::INVALID_PARAMS => "invalid params",
        code::INTERNAL => "internal error",
        code::SESSION_LOCKED => "vault is locked",
        code::INVALID_VAULT_PATH => "invalid vault path",
        code::VAULT_NOT_FOUND => "vault not found",
        code::DECRYPTION_FAILED => "wrong password",
        code::NOT_FOUND => "entry not found",
        code::UNKNOWN_METHOD => "method not implemented by this service",
        code::OVERSIZED => "payload too large",
        code::UNAUTHORIZED => "auth failed",
        code::REPLAY => "replay detected",
        _ => "daemon error",
    }
}

/// Read one request from `r`, dispatch against `state` via
/// `service`, and write the response to `w`. Generic over the
/// reader and writer so tests can use in-memory buffers.
pub fn handle_one<R: Read, W: Write, S: VaultService>(
    state: &Mutex<DaemonState>,
    service: &S,
    r: &mut R,
    w: &mut W,
) -> std::io::Result<()> {
    // [BITNET-M4] CWE-400: bound the entire request-handling
    // time with a deadline. The underlying transport may
    // already have a per-read timeout installed (Windows
    // Named Pipe via `SetCommTimeouts`); the soft deadline
    // here is the cross-platform fallback for in-memory
    // test transports and any future non-Windows Named-Pipe
    // equivalent.
    let deadline = std::time::Instant::now() + protocol::MAX_REQUEST_DURATION;
    let request_value = protocol::read_frame_with_deadline(r, Some(deadline))?;
    let request: Request = serde_json::from_value(request_value)
        .map_err(|e| std::io::Error::new(std::io::ErrorKind::InvalidData, e))?;
    let response = dispatch(state, service, request);
    protocol::write_frame(w, &response)
}

/// Read one request and write one response using a single
/// `&mut Conn` (the connection serves as both reader and
/// writer). Used by the long-running `run_daemon` loop where
/// the OS gives us one bidirectional handle per client.
///
/// Implementation note: the caller's `accept()` loop will
/// call `Server::accept()` again on the next iteration,
/// which re-binds the same handle via `ConnectNamedPipe`.
/// `Conn::Drop` then disconnects the just-finished
/// connection.
pub fn handle_one_in_memory<S: VaultService>(
    state: &Mutex<DaemonState>,
    service: &S,
    conn: &mut Conn,
) -> std::io::Result<()> {
    let request_value = protocol::read_frame(&mut *conn)?;
    let request: Request = serde_json::from_value(request_value)
        .map_err(|e| std::io::Error::new(std::io::ErrorKind::InvalidData, e))?;
    let response = dispatch(state, service, request);
    protocol::write_frame(&mut *conn, &response)
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::io::Cursor;

    /// Current Unix timestamp in seconds. Used as `ts` in
    /// HMAC-signed requests so the freshness check accepts them.
    fn now_ts() -> u64 {
        std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .map(|d| d.as_secs())
            .unwrap_or(0)
    }

    fn empty_request(id: u64, method: &str) -> Request {
        Request {
            jsonrpc: "2.0".into(),
            id,
            method: method.into(),
            params: serde_json::json!({}),
            auth: None,
            seq: None,
            ts: None,
        }
    }

    #[test]
    fn new_state_is_locked() {
        let s = DaemonState::new();
        assert!(!s.has_token());
        assert!(s.token().is_none());
    }

    #[test]
    fn set_and_clear_token() {
        let mut s = DaemonState::new();
        s.set_token([7u8; 32]);
        assert!(s.has_token());
        assert_eq!(s.token(), Some(&[7u8; 32]));
        let was_present = s.clear_token();
        assert!(was_present);
        assert!(!s.has_token());
    }

    #[test]
    fn clear_token_on_empty_returns_false() {
        let mut s = DaemonState::new();
        assert!(!s.clear_token());
    }

    #[test]
    fn drop_state_zeroises_token() {
        let mut s = DaemonState::new();
        s.set_token([42u8; 32]);
        drop(s);
        let s2 = DaemonState::new();
        assert!(!s2.has_token());
    }

    #[test]
    fn ping_bypasses_auth() {
        let state = Mutex::new(DaemonState::new());
        let svc = NoopVaultService;
        let resp = dispatch(&state, &svc, empty_request(1, "ping"));
        assert_eq!(resp["result"]["pong"], true);
    }

    #[test]
    fn protected_methods_require_token() {
        let state = Mutex::new(DaemonState::new());
        let svc = NoopVaultService;
        let resp = dispatch(&state, &svc, empty_request(3, "list_entries"));
        assert_eq!(resp["error"]["code"], code::SESSION_LOCKED);
    }

    #[test]
    fn protected_methods_require_valid_hmac() {
        let state = Mutex::new(DaemonState::new());
        state.lock().unwrap().set_token([0u8; 32]);
        let svc = NoopVaultService;
        let bad_auth = crate::auth::sign_request(b"wrong-key", "list_entries", b"{}", 1, now_ts());
        let mut req = empty_request(3, "list_entries");
        req.auth = Some(bad_auth);
        req.seq = Some(1);
        req.ts = Some(now_ts());
        let resp = dispatch(&state, &svc, req);
        assert_eq!(resp["error"]["code"], code::UNAUTHORIZED);
    }

    #[test]
    fn protected_methods_accept_valid_hmac() {
        let state = Mutex::new(DaemonState::new());
        let token = [1u8; 32];
        state.lock().unwrap().set_token(token);
        let svc = NoopVaultService;
        // NoopVaultService rejects list_entries with UNKNOWN_METHOD,
        // so the response is an error envelope — but a `result`
        // field is the wrong type. Adjust the assertion to check
        // that auth passed: the error code should be UNKNOWN_METHOD
        // (not UNAUTHORIZED or SESSION_LOCKED).
        let now = now_ts();
        let good_auth = crate::auth::sign_request(&token, "list_entries", b"{}", 1, now);
        let mut req = empty_request(3, "list_entries");
        req.auth = Some(good_auth);
        req.seq = Some(1);
        req.ts = Some(now);
        let resp = dispatch(&state, &svc, req);
        assert_eq!(resp["error"]["code"], code::UNKNOWN_METHOD);
    }

    #[test]
    fn unlock_sets_token_and_returns_hex() {
        let state = Mutex::new(DaemonState::new());
        let svc = NoopVaultService;
        // [BITNET-H1] unlock no longer returns token_hex — only
        // an ack. The token is supplied in params and stored.
        let mut req = empty_request(1, "unlock");
        req.params = serde_json::json!({
            "path": "/vault.bitnet",
            "token_hex": "000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f"
        });
        let resp = dispatch(&state, &svc, req);
        assert_eq!(resp["result"]["ok"], true);
        // The token is stored verbatim (client-supplied).
        assert!(state.lock().unwrap().has_token());
    }

    #[test]
    fn lock_drops_token_with_valid_hmac() {
        let state = Mutex::new(DaemonState::new());
        let token = [9u8; 32];
        {
            let mut g = state.lock().unwrap();
            g.set_token(token);
        }
        let svc = NoopVaultService;
        let now = now_ts();
        let auth = crate::auth::sign_request(&token, "lock", b"{}", 1, now);
        let mut req = empty_request(4, "lock");
        req.auth = Some(auth);
        req.seq = Some(1);
        req.ts = Some(now);
        let resp = dispatch(&state, &svc, req);
        assert_eq!(resp["result"]["ok"], true);
        assert!(!state.lock().unwrap().has_token());
    }

    #[test]
    fn is_unlocked_reports_token_state() {
        let mut s = DaemonState::new();
        assert!(!s.has_token());
        s.set_token([0u8; 32]);
        assert!(s.has_token());
    }

    #[test]
    fn unknown_method_returns_error_code() {
        let state = Mutex::new(DaemonState::new());
        let svc = NoopVaultService;
        let resp = dispatch(&state, &svc, empty_request(1, "definitely_not_a_method"));
        assert_eq!(resp["error"]["code"], code::UNKNOWN_METHOD);
    }

    #[test]
    fn full_roundtrip_via_handle_one() {
        let state = Mutex::new(DaemonState::new());
        let token = [5u8; 32];
        state.lock().unwrap().set_token(token);
        let svc = NoopVaultService;

        let now = now_ts();
        let req = Request {
            jsonrpc: "2.0".into(),
            id: 99,
            method: "list_entries".into(),
            params: serde_json::json!({}),
            auth: Some(crate::auth::sign_request(
                &token,
                "list_entries",
                b"{}",
                1,
                now,
            )),
            seq: Some(1),
            ts: Some(now),
        };
        let body = serde_json::to_value(&req).unwrap();
        let mut sink: Vec<u8> = Vec::new();
        protocol::write_frame(&mut sink, &body).unwrap();
        let mut cur = Cursor::new(sink);

        let mut out: Vec<u8> = Vec::new();
        handle_one(&state, &svc, &mut cur, &mut out).unwrap();

        let resp = protocol::read_frame(&mut Cursor::new(out)).unwrap();
        assert_eq!(resp["id"], 99);
        // NoopVaultService rejects list_entries with UNKNOWN_METHOD.
        assert_eq!(resp["error"]["code"], code::UNKNOWN_METHOD);
    }

    #[test]
    fn unlock_then_lock_roundtrip() {
        // Realistic flow: daemon starts locked, a client unlocks
        // (no auth required, client supplies token), then locks
        // (auth required). Verifies the supplied token is the one
        // that authenticates the lock.
        let state = Mutex::new(DaemonState::new());
        let svc = NoopVaultService;

        // Step 1: unlock with a client-supplied token.
        let supplied_token = [0xab; 32];
        let token_hex: String = (0..32)
            .map(|i| format!("{:02x}", supplied_token[i]))
            .collect();
        let mut unlock_req = empty_request(1, "unlock");
        unlock_req.params = serde_json::json!({
            "path": "/vault.bitnet",
            "token_hex": token_hex,
        });
        let unlock_resp = dispatch(&state, &svc, unlock_req);
        assert_eq!(unlock_resp["result"]["ok"], true);

        // [BITNET-H1] The response no longer carries `token_hex`.
        assert!(unlock_resp["result"].get("token_hex").is_none());
        let token = supplied_token;

        // Step 2: is_unlocked without auth → UNAUTHORIZED.
        let is_resp = dispatch(&state, &svc, empty_request(2, "is_unlocked"));
        assert_eq!(is_resp["error"]["code"], code::UNAUTHORIZED);

        // Step 3: sign a request with the supplied token.
        let now = now_ts();
        let auth = crate::auth::sign_request(&token, "is_unlocked", b"{}", 1, now);
        let mut req = empty_request(3, "is_unlocked");
        req.auth = Some(auth);
        req.seq = Some(1);
        req.ts = Some(now);
        let is_resp = dispatch(&state, &svc, req);
        assert_eq!(is_resp["result"]["unlocked"], true);

        // Step 4: lock with the same token.
        let now2 = now_ts();
        let auth = crate::auth::sign_request(&token, "lock", b"{}", 2, now2);
        let mut req = empty_request(4, "lock");
        req.auth = Some(auth);
        req.seq = Some(2);
        req.ts = Some(now2);
        let lock_resp = dispatch(&state, &svc, req);
        assert_eq!(lock_resp["result"]["ok"], true);
        assert!(!state.lock().unwrap().has_token());
    }

    /// [BITNET-M3] Regression: a captured frame with a valid HMAC
    /// must NOT be re-playable. The daemon's monotonic-seq check
    /// must reject any request with `seq <= last_seen`.
    #[test]
    fn replay_with_stale_seq_is_rejected() {
        let state = Mutex::new(DaemonState::new());
        let token = [7u8; 32];
        state.lock().unwrap().set_token(token);
        let svc = NoopVaultService;

        // First request with seq=5 passes the auth/HMAC check
        // (but fails on UNKNOWN_METHOD because list_entries
        // is not implemented by NoopVaultService).
        let now = now_ts();
        let auth = crate::auth::sign_request(&token, "list_entries", b"{}", 5, now);
        let mut req = empty_request(1, "list_entries");
        req.auth = Some(auth);
        req.seq = Some(5);
        req.ts = Some(now);
        let resp = dispatch(&state, &svc, req);
        // Authenticated, but list_entries is not implemented
        // (UNKNOWN_METHOD), proving the HMAC+seq check passed.
        assert_eq!(resp["error"]["code"], code::UNKNOWN_METHOD);

        // Re-send the same frame (or any frame with seq <= 5).
        let now2 = now_ts();
        let auth = crate::auth::sign_request(&token, "list_entries", b"{}", 5, now2);
        let mut req = empty_request(2, "list_entries");
        req.auth = Some(auth);
        req.seq = Some(5);
        req.ts = Some(now2);
        let resp = dispatch(&state, &svc, req);
        // The seq check kicks in BEFORE the auth verify, so the
        // error is REPLAY.
        assert_eq!(resp["error"]["code"], code::REPLAY);
    }

    /// [BITNET-M3] A request without `seq` and `ts` is rejected
    /// as a replay attempt (it could not be authenticated against
    /// the fresh-only HMAC).
    #[test]
    fn missing_seq_ts_is_rejected() {
        let state = Mutex::new(DaemonState::new());
        let token = [3u8; 32];
        state.lock().unwrap().set_token(token);
        let svc = NoopVaultService;

        let auth = crate::auth::sign_request(&token, "list_entries", b"{}", 0, 0);
        let mut req = empty_request(1, "list_entries");
        req.auth = Some(auth);
        // seq and ts left as None on purpose.
        let resp = dispatch(&state, &svc, req);
        assert_eq!(resp["error"]["code"], code::REPLAY);
    }

    /// [BITNET-S1] shutdown sets the AtomicBool flag in
    /// DaemonState and returns ok.
    #[test]
    fn shutdown_sets_shutdown_flag() {
        let state = Mutex::new(DaemonState::new());
        let svc = NoopVaultService;
        let req = empty_request(1, "shutdown");
        let resp = dispatch(&state, &svc, req);
        assert_eq!(resp["result"]["ok"], true);
        assert!(
            state.lock().unwrap().shutdown.load(std::sync::atomic::Ordering::SeqCst),
            "shutdown flag must be set"
        );
    }

    /// [BITNET-S1] shutdown requires no authentication.
    #[test]
    fn shutdown_is_auth_free() {
        let state = Mutex::new(DaemonState::new());
        let svc = NoopVaultService;
        let req = empty_request(1, "shutdown");
        let resp = dispatch(&state, &svc, req);
        assert_eq!(resp["error"], serde_json::Value::Null);
        assert_eq!(resp["result"]["ok"], true);
    }

    /// [BITNET-S1] shutdown does not mutate the token.
    #[test]
    fn shutdown_preserves_token_when_unlocked() {
        let state = Mutex::new(DaemonState::new());
        let token = [7u8; 32];
        state.lock().unwrap().set_token(token);
        let svc = NoopVaultService;
        let req = empty_request(1, "shutdown");
        let resp = dispatch(&state, &svc, req);
        assert_eq!(resp["result"]["ok"], true);
        assert!(state.lock().unwrap().has_token(), "token must survive shutdown request");
    }
}
