a = Analysis(
    ['launcher.py'],
    pathex=['..'],
    binaries=[],
    datas=[
        ('../frontend/dist', 'frontend/dist'),
        ('../alembic', 'alembic'),
        ('../alembic.ini', '.'),
        ('../backend/core/bitnet_crypto_rs.pyd', 'backend/core'),
    ],
    hiddenimports=[
        'uvicorn.logging',
        'uvicorn.loops',
        'uvicorn.loops.auto',
        'uvicorn.protocols',
        'uvicorn.protocols.http',
        'uvicorn.protocols.http.auto',
        'uvicorn.protocols.websockets',
        'uvicorn.protocols.websockets.auto',
        'uvicorn.lifespan',
        'uvicorn.lifespan.on',
        'backend.core.bitnet_crypto_rs',
        'backend.core.crypto_bridge',
        'backend.core.crypto_core',
        'backend.core.encryption_helper',
        'backend.core.security_utils',
        'backend.core.auth_manager',
        'backend.core.config',
        'backend.core.audit_logger',
        'backend.core.secure_delete',
        'backend.core.secure_heap',
        'backend.core.advanced_security',
        'backend.core.pypy_optimization',
        'backend.database.session',
        'backend.database.models',
        'backend.database.schemas',
        'backend.database.entry_service',
        'backend.database.db_optimization',
        'backend.database.db_security',
        'backend.api.v1.endpoints.auth',
        'backend.api.v1.endpoints.entries',
        'backend.api.v1.endpoints.trash',
        'backend.api.v1.endpoints.fido2',
        'backend.api.v1.endpoints.generator',
        'backend.api.v1.endpoints.portability',
        'backend.api.v1.endpoints.backups',
        'backend.api.v1.endpoints.breach',
        'backend.features.backup_manager',
        'backend.features.breach_monitor_async',
        'backend.features.password_generator',
        'backend.features.password_history_manager',
        'backend.features.qr_generator',
        'backend.features.search_engine',
        'backend.services.import_export',
        'email_validator',
        'argon2',
        'nacl',
        'cryptography',
        'sqlalchemy.dialects.sqlite',
        'sqlalchemy.ext.asyncio',
        'aiosqlite',
        'pydantic_settings',
        'multipart',
        'webauthn',
        'qrcode',
        'PIL',
        'httpx',
        'httpcore',
        'anyio',
        'sniffio',
        'h11',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'pytest',
        'hypothesis',
        'bandit',
        'safety',
        'black',
        'flake8',
        'mypy',
        'pylint',
        'pre_commit',
        'coverage',
        'playwright',
    ],
    noarchive=False,
)

pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='BitNet',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=True,
    icon=None,
)

coll = COLLECT(
    exe,
    a.binaries,
    a.datas,
    a.zipfiles,
    strip=False,
    upx=True,
    upx_exclude=[],
    name='BitNet',
)